/**
 * Copyright (C) 2022-2024 Permanent Data Solutions, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Off-chain prediction of `prescribe_epoch`'s observer selection.
 *
 * `ario_gar::prescribe_epoch` selects observers INTERNALLY via a weighted
 * roulette over the `GatewayRegistry`, then uses `remaining_accounts` only as a
 * lookup table for the ~50 selected Gateway PDAs (+ NameRegistry). A cranker
 * that instead supplies every registry gateway hits Solana's
 * `MAX_TX_ACCOUNT_LOCKS = 64` on large registries and the tx is rejected at
 * pre-flight. This helper mirrors the on-chain selection so the caller can
 * supply exactly the selected set.
 *
 * The selection is deterministic from on-chain state that is stable once
 * `epoch.weights_tallied == 1`: the frozen `epoch.hashchain` entropy beacon and
 * the live `registry.gateways[*].composite_weight`.
 *
 * Cross-language parity with the Rust handler
 * (`ar-io-solana-contracts/programs/ario-gar/src/instructions/epoch.rs`, the
 * `prescribe_epoch` observer-selection block) is asserted in
 * `predict-prescribed-observers.test.ts` against vectors generated by the Rust
 * reference example `programs/ario-gar/examples/predict_prescribed_observers.rs`.
 * If you change this algorithm, update that example and the test together.
 */
import { createHash } from 'crypto';

import { type Address } from '@solana/kit';

/** One registry slot's selection-relevant fields (`GatewaySlot`). */
export interface RegistrySlotWeight {
  /** `GatewaySlot.address` — the operator pubkey. Gateway PDAs derive from this. */
  address: Address;
  /** `GatewaySlot.composite_weight` (u64, mARIO-scaled). */
  compositeWeight: bigint;
}

function sha256(data: Uint8Array): Buffer {
  return createHash('sha256').update(data).digest();
}

/** `u128::from_le_bytes(bytes[0..16])` — little-endian, first 16 bytes only. */
function leU128(bytes: Uint8Array): bigint {
  let v = 0n;
  for (let i = 15; i >= 0; i--) {
    v = (v << 8n) | BigInt(bytes[i]);
  }
  return v;
}

/**
 * Predict the operator pubkeys `prescribe_epoch` will select as observers.
 *
 * Returns the selected `GatewaySlot.address` values (operator pubkeys) in
 * selection order, at most `maxObservers`. These correspond 1:1 to the on-chain
 * `epoch.prescribed_observer_gateways` array, and are what Gateway PDAs are
 * derived from (`[GATEWAY_SEED, operator]`). NOTE this is NOT
 * `epoch.prescribed_observers`, which `prescribe_epoch` later overwrites with
 * each gateway's resolved `observer_address`.
 *
 * @param epochHashchain `epoch.hashchain` — exactly 32 bytes, frozen at
 *   `create_epoch`.
 * @param slots `registry.gateways[0 .. epoch.active_gateway_count]` in registry
 *   (slot-index) order. Pass the whole prefix including any zero-weight slots —
 *   order and the live weight sum must match the on-chain walk exactly. Empty /
 *   zero-weight slots contribute nothing and can never be selected.
 * @param maxObservers `epoch_settings.prescribed_observer_count`. Clamped to
 *   `slots.length` (the on-chain `min(prescribed_observer_count, active_count)`).
 */
export function predictPrescribedObservers(
  epochHashchain: Uint8Array,
  slots: RegistrySlotWeight[],
  maxObservers: number,
): Address[] {
  if (epochHashchain.length !== 32) {
    throw new Error(
      `epochHashchain must be 32 bytes, got ${epochHashchain.length}`,
    );
  }

  const activeCount = slots.length;
  const cap = Math.min(maxObservers, activeCount);

  // Live total weight (epoch.rs: `for i in 0..active_count { total += w }`).
  // u128 sum of u64 weights over <=3000 slots cannot overflow, so the Rust
  // `saturating_add` never actually saturates; plain BigInt addition matches.
  let totalWeight = 0n;
  for (const slot of slots) {
    totalWeight += slot.compositeWeight;
  }

  const selected: Address[] = [];
  if (totalWeight === 0n || activeCount === 0 || cap === 0) {
    return selected;
  }

  // Initial entropy: sha256(hashchain).
  let hashBytes = sha256(epochHashchain);

  // GAR-019: bounded retries, up to cap * 10 rounds.
  const maxRounds = cap * 10;
  for (let round = 0; round < maxRounds; round++) {
    if (selected.length >= cap) break;

    const randomValue = leU128(hashBytes.subarray(0, 16)) % totalWeight;

    let cumulative = 0n;
    for (const slot of slots) {
      cumulative += slot.compositeWeight;
      if (cumulative > randomValue && slot.compositeWeight > 0n) {
        // Anti-duplicate: skip if already chosen, but the round still consumes
        // the roulette hit — break the walk either way (epoch.rs).
        if (!selected.includes(slot.address)) {
          selected.push(slot.address);
        }
        break;
      }
    }

    // Re-hash for the next round: sha256(hash_bytes).
    hashBytes = sha256(hashBytes);
  }

  return selected;
}
